# Generated by Django 2.2 on 2019-04-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_productinbasket123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInBasket123',
        ),
    ]
