# Generated by Django 2.2 on 2019-04-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_productinbasket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='session_key',
        ),
    ]
