# Generated by Django 2.2 on 2019-04-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product123',
        ),
    ]
